#!/bin/bash
docker-compose -f nginx/compose.yml down --volumes
docker-compose -f one/compose.yml down --volumes
docker-compose -f two/compose.yml down --volumes
docker-compose -f db/compose.yml down --volumes