services:
  two:
    build: ./
    container_name: two
    networks:
      - nginx_network      # proxy and app must be in same network
    volumes:
      - ./src:/app
networks:
  nginx_network:
    external: true
# version: "3.9"
# services:
#   web:
#     build: ./
#     hostname: two
#     networks:
#       - two
#     volumes:
#       - ./src:/app
# networks:
#   nginx:
#     external: true
#   two: