services:
  one:
    build: ./
    container_name: one
    networks:
      - nginx_network      # proxy and app must be in same network
    volumes:
      - ./src:/app
networks:
  nginx_network:
    external: true

# version: "3.9"
# services:
#   web:
#     build: ./
#     networks:
#       one:
#       nginx_web:
#         ipv4_address: 172.17.0.40
#     volumes:
#       - ./src:/app
#     ports:
#       - 3000:3000
# networks:
#   nginx_web:
#   one:
