services:
  server:
    build: ./
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_network
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites:/etc/nginx/sites-enabled/
      - ./certs:/etc/letsencrypt/
networks:
  nginx_network:
    external: true