services:
  server:
    build: ./
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_network
    volumes:
      - ./sites:/etc/nginx/sites-enabled/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
networks:
  nginx_network:
    external: true

